### ISSUE TITLE
macOS shows nothing and keeps loading

### ISSUE THREAD

**Issue by lvyandev** [fluttertools/sidekick#297]
```console
[✓] Flutter (Channel stable, 3.10.5, on macOS 13.3.1 22E772610a darwin-x64, locale zh-Hans-CN)
    • Flutter version 3.10.5 on channel stable at /Users/lvyan/development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 796c8ef792 (2 weeks ago), 2023-06-13 15:51:02 -0700
    • Engine revision 45f6e00911
    • Dart version 3.0.5
    • DevTools version 2.23.1
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/lvyan/Library/Android/sdk
    • Platform android-33, build-tools 31.0.0
    • ANDROID_HOME = /Users/lvyan/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS (Xcode 14.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E222b
    ! CocoaPods 1.10.1 out of date (1.11.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart
        side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade see https://guides.cocoapods.org/using/getting-started.html#installation for instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[✓] IntelliJ IDEA Community Edition (version 2021.1.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.67.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Proxy Configuration
    • HTTP_PROXY is set
    • NO_PROXY is localhost,127.0.0.1,localaddress,.localdomain.com,::1
    • NO_PROXY contains localhost
    • NO_PROXY contains 127.0.0.1
    • NO_PROXY contains ::1

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 13.3.1 22E772610a darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 114.0.5735.198

[✓] Network resources
    • All expected network resources are available.

```

<img width="912" alt="image" src="https://github.com/fluttertools/sidekick/assets/18045999/3072d8d3-0f20-410a-9013-8bfa07f473f5">
<img width="912" alt="image" src="https://github.com/fluttertools/sidekick/assets/18045999/1c91e1a0-ae7f-4fc7-82e9-c77c619218b7">

**Comment by lvyandev** [comment]
Sure, I will give it a try later this evening.

**Comment by lvyandev** [comment]
strange thing is that debug runs well
all I got on the console is just
```
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Operation timed out
#0      IOClient.send (package:http/src/io_client.dart:96:7)
<asynchronous suspension>
#1      BaseClient._sendUnstreamed (package:http/src/base_client.dart:93:32)
<asynchronous suspension>
#2      _withClient (package:http/http.dart:166:12)
<asynchronous suspension>
#3      UpdaterService.downloadRelease (package:sidekick/src/modules/updater/updater.service.dart:56:17)
<asynchronous suspension>
#4      UpdaterStateNotifier.download (package:sidekick/src/modules/updater/updater.provider.dart:35:13)
<asynchronous suspension>
#5      UpdaterStateNotifier.checkLatest (package:sidekick/src/modules/updater/updater.provider.dart:29:7)
<asynchronous suspension>

```

**Comment by lvyandev** [comment]
It also happens on another device today, a MacBookPro M1. While the app behaved normally before.

**Comment by wangdean** [comment]
same error

**Comment by aguilaair** [comment]
Do you normally need a proxy?

**Comment by aguilaair** [comment]
I suspect that is the cause, then!

**Comment by aguilaair** [comment]
I'll change this issue to make the update service not halt the rest of the app, but unfortunately, the root issue is a known Flutter bug, which causes it to ignore Proxy settings.

**Comment by charles0122** [comment]
@lvyandev @wangdean I think it's a network issue.
@aguilaair Sidekick doesn't seem to change the user's proxy settings, so I don't think it has anything to do with Sidekick
